# Generated by Django 3.2 on 2021-04-18 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('operatorID', models.CharField(default=None, max_length=30, unique=True, verbose_name='Operator ID')),
                ('OPRpassword', models.CharField(default=None, max_length=30, verbose_name='Password')),
                ('permission', models.CharField(choices=[('Read + Modify', 'Read + Modify'), ('Read Only', 'Read Only')], default=None, max_length=30, verbose_name='Permission')),
                ('dateSignUp', models.DateField(auto_now=True, verbose_name='Date Signed Up')),
            ],
            options={
                'db_table': 'operator_table',
            },
        ),
    ]
