# Generated by Django 3.2 on 2021-04-20 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Operator', '0002_operator_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operator',
            name='id',
        ),
        migrations.AlterField(
            model_name='operator',
            name='permission',
            field=models.CharField(choices=[('Read Only', 'Read Only'), ('Read + Modify', 'Read + Modify')], default=None, max_length=30, verbose_name='Permission'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
