# Generated by Django 3.2 on 2021-05-13 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(blank=True, choices=[('DORVAL', 'DORVAL'), ('SEOYANG', 'SEOYANG'), ('SHI OCEAN', 'SHI OCEAN'), ('STX', 'STX'), ('SUNAMI', 'SUNAMI'), ('CENTRA', 'CENTRA'), ('POSSM', 'POSSM'), ('KNK', 'KNK'), ('이강공사', '이강공사'), ('SAEHAN', 'SAEHAN'), ('JW', 'JW'), ('DAN MO', 'DAN MO'), ('INTERGIS', 'INTERGIS'), ('EUCO', 'EUCO'), ('GOWIN', 'GOWIN'), ('보성상사', '보성상사'), ('GOLTENS', 'GOLTENS'), ('CMSHIP', 'CMSHIP'), ('MARUBISHI', 'MARUBISHI'), ('오션마린', '오션마린'), ('FORTUNE WILL', 'FORTUNE WILL'), ('KSS', 'KSS'), ('MAN', 'MAN'), ('KLCSM', 'KLCSM'), ('SUNRIO', 'SUNRIO'), ('GLOVIS', 'GLOVIS')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('D', 'D'), ('L', 'L')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('BLANK', 'BLANK'), ('STAY1', 'STAY1'), ('COMPLETED', 'COMPLETED'), ('START', 'START'), ('STAY2', 'STAY2')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
    ]
