# Generated by Django 3.2 on 2021-04-21 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='by',
            field=models.CharField(blank=True, choices=[('SFX', 'SFX'), ('TNT', 'TNT'), ('SEA', 'SEA'), ('DHL', 'DHL'), ('FDX', 'FDX'), ('AIR', 'AIR')], db_column='by1', max_length=50, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(choices=[('KLCSM', 'KLCSM'), ('CENTRA', 'CENTRA'), ('EUCO', 'EUCO'), ('KSS', 'KSS'), ('MAN', 'MAN'), ('POSSM', 'POSSM'), ('SEOYANG', 'SEOYANG'), ('DORVAL', 'DORVAL'), ('GOLTENS', 'GOLTENS'), ('SAEHAN', 'SAEHAN'), ('STX', 'STX'), ('CMSHIP', 'CMSHIP'), ('이강공사', '이강공사'), ('MARUBISHI', 'MARUBISHI'), ('GLOVIS', 'GLOVIS'), ('DAN MO', 'DAN MO'), ('SUNRIO', 'SUNRIO'), ('오션마린', '오션마린'), ('FORTUNE WILL', 'FORTUNE WILL'), ('GOWIN', 'GOWIN'), ('보성상사', '보성상사'), ('INTERGIS', 'INTERGIS'), ('KNK', 'KNK'), ('SUNAMI', 'SUNAMI'), ('SHI OCEAN', 'SHI OCEAN')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('D', 'D'), ('B', 'B'), ('L', 'L')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('STAY', 'STAY'), ('COMPLETED', 'COMPLETED'), ('START', 'START'), ('BLANK', 'BLANK')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='warehouse',
            field=models.CharField(blank=True, choices=[('SL', 'SL'), ('ICN-IGS', 'ICN-IGS'), ('KIM-IGS', 'KIM-IGS')], db_column='whouse', max_length=100, verbose_name='W/H'),
        ),
    ]
