# Generated by Django 3.2 on 2021-04-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='by',
            field=models.CharField(blank=True, choices=[('DHL', 'DHL'), ('SFX', 'SFX'), ('TNT', 'TNT'), ('SEA', 'SEA'), ('AIR', 'AIR'), ('FDX', 'FDX')], db_column='by1', max_length=50, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(blank=True, choices=[('MAN', 'MAN'), ('MARUBISHI', 'MARUBISHI'), ('SAEHAN', 'SAEHAN'), ('오션마린', '오션마린'), ('이강공사', '이강공사'), ('INTERGIS', 'INTERGIS'), ('KLCSM', 'KLCSM'), ('KSS', 'KSS'), ('SHI OCEAN', 'SHI OCEAN'), ('STX', 'STX'), ('SUNRIO', 'SUNRIO'), ('CENTRA', 'CENTRA'), ('CMSHIP', 'CMSHIP'), ('POSSM', 'POSSM'), ('GOLTENS', 'GOLTENS'), ('보성상사', '보성상사'), ('DAN MO', 'DAN MO'), ('FORTUNE WILL', 'FORTUNE WILL'), ('DORVAL', 'DORVAL'), ('KNK', 'KNK'), ('GLOVIS', 'GLOVIS'), ('SEOYANG', 'SEOYANG'), ('SUNAMI', 'SUNAMI'), ('JW', 'JW'), ('EUCO', 'EUCO'), ('GOWIN', 'GOWIN')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('D', 'D'), ('L', 'L')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'COMPLETED'), ('START', 'START'), ('BLANK', 'BLANK'), ('STAY', 'STAY')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='out_date',
            field=models.DateField(blank=True, db_column='out1', max_length=10, null=True, verbose_name='OUT'),
        ),
    ]
