# Generated by Django 3.2 on 2021-04-23 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0002_auto_20210421_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='by',
            field=models.CharField(blank=True, choices=[('DHL', 'DHL'), ('TNT', 'TNT'), ('FDX', 'FDX'), ('AIR', 'AIR'), ('SFX', 'SFX'), ('SEA', 'SEA')], db_column='by1', max_length=50, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(choices=[('KSS', 'KSS'), ('EUCO', 'EUCO'), ('POSSM', 'POSSM'), ('SAEHAN', 'SAEHAN'), ('GOLTENS', 'GOLTENS'), ('이강공사', '이강공사'), ('MAN', 'MAN'), ('오션마린', '오션마린'), ('DAN MO', 'DAN MO'), ('STX', 'STX'), ('KLCSM', 'KLCSM'), ('SUNRIO', 'SUNRIO'), ('KNK', 'KNK'), ('FORTUNE WILL', 'FORTUNE WILL'), ('SUNAMI', 'SUNAMI'), ('GOWIN', 'GOWIN'), ('SHI OCEAN', 'SHI OCEAN'), ('INTERGIS', 'INTERGIS'), ('SEOYANG', 'SEOYANG'), ('CMSHIP', 'CMSHIP'), ('GLOVIS', 'GLOVIS'), ('MARUBISHI', 'MARUBISHI'), ('CENTRA', 'CENTRA'), ('보성상사', '보성상사'), ('DORVAL', 'DORVAL')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('L', 'L'), ('D', 'D'), ('B', 'B')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'COMPLETED'), ('BLANK', 'BLANK'), ('START', 'START'), ('STAY', 'STAY')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='odr',
            field=models.TextField(blank=True, db_column='odr', max_length=100, verbose_name='ODR'),
        ),
    ]
