# Generated by Django 3.2 on 2021-05-16 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0002_auto_20210514_0456'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='colorpick',
            field=models.CharField(db_column='color_status', default='#FFFFFF', max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(blank=True, choices=[('DAN MO', 'DAN MO'), ('KSS', 'KSS'), ('JW', 'JW'), ('EUCO', 'EUCO'), ('GOWIN', 'GOWIN'), ('KLCSM', 'KLCSM'), ('KNK', 'KNK'), ('SHI OCEAN', 'SHI OCEAN'), ('오션마린', '오션마린'), ('SAEHAN', 'SAEHAN'), ('이강공사', '이강공사'), ('GLOVIS', 'GLOVIS'), ('SUNRIO', 'SUNRIO'), ('MARUBISHI', 'MARUBISHI'), ('INTERGIS', 'INTERGIS'), ('보성상사', '보성상사'), ('CMSHIP', 'CMSHIP'), ('MAN', 'MAN'), ('DORVAL', 'DORVAL'), ('FORTUNE WILL', 'FORTUNE WILL'), ('STX', 'STX'), ('CENTRA', 'CENTRA'), ('GOLTENS', 'GOLTENS'), ('POSSM', 'POSSM'), ('SEOYANG', 'SEOYANG'), ('SUNAMI', 'SUNAMI')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('L', 'L'), ('B', 'B'), ('D', 'D')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'COMPLETED'), ('START', 'START'), ('STAY2', 'STAY2'), ('STAY1', 'STAY1'), ('BLANK', 'BLANK')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
    ]
