# Generated by Django 3.2 on 2021-05-16 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0003_auto_20210516_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='colorpick',
            field=models.CharField(blank=True, db_column='color_status', default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(blank=True, choices=[('이강공사', '이강공사'), ('POSSM', 'POSSM'), ('SHI OCEAN', 'SHI OCEAN'), ('STX', 'STX'), ('GOWIN', 'GOWIN'), ('DORVAL', 'DORVAL'), ('KLCSM', 'KLCSM'), ('KSS', 'KSS'), ('SAEHAN', 'SAEHAN'), ('GOLTENS', 'GOLTENS'), ('SUNAMI', 'SUNAMI'), ('CMSHIP', 'CMSHIP'), ('JW', 'JW'), ('MARUBISHI', 'MARUBISHI'), ('보성상사', '보성상사'), ('GLOVIS', 'GLOVIS'), ('DAN MO', 'DAN MO'), ('FORTUNE WILL', 'FORTUNE WILL'), ('KNK', 'KNK'), ('오션마린', '오션마린'), ('MAN', 'MAN'), ('CENTRA', 'CENTRA'), ('EUCO', 'EUCO'), ('INTERGIS', 'INTERGIS'), ('SUNRIO', 'SUNRIO'), ('SEOYANG', 'SEOYANG')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('D', 'D'), ('L', 'L')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('STAY1', 'STAY1'), ('STAY2', 'STAY2'), ('BLANK', 'BLANK'), ('COMPLETED', 'COMPLETED'), ('START', 'START')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
    ]
