# Generated by Django 3.2 on 2021-04-23 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0003_auto_20210423_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='by',
            field=models.CharField(blank=True, choices=[('TNT', 'TNT'), ('SFX', 'SFX'), ('FDX', 'FDX'), ('DHL', 'DHL'), ('SEA', 'SEA'), ('AIR', 'AIR')], db_column='by1', max_length=50, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(choices=[('SAEHAN', 'SAEHAN'), ('SEOYANG', 'SEOYANG'), ('CMSHIP', 'CMSHIP'), ('EUCO', 'EUCO'), ('GLOVIS', 'GLOVIS'), ('INTERGIS', 'INTERGIS'), ('KNK', 'KNK'), ('FORTUNE WILL', 'FORTUNE WILL'), ('KLCSM', 'KLCSM'), ('SUNAMI', 'SUNAMI'), ('POSSM', 'POSSM'), ('MARUBISHI', 'MARUBISHI'), ('STX', 'STX'), ('SUNRIO', 'SUNRIO'), ('GOWIN', 'GOWIN'), ('SHI OCEAN', 'SHI OCEAN'), ('DAN MO', 'DAN MO'), ('오션마린', '오션마린'), ('CENTRA', 'CENTRA'), ('MAN', 'MAN'), ('이강공사', '이강공사'), ('KSS', 'KSS'), ('보성상사', '보성상사'), ('GOLTENS', 'GOLTENS'), ('DORVAL', 'DORVAL')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('D', 'D'), ('L', 'L')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'COMPLETED'), ('START', 'START'), ('BLANK', 'BLANK'), ('STAY', 'STAY')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='in_date',
            field=models.CharField(blank=True, db_column='in1', max_length=10, null=True, verbose_name='IN'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='out_date',
            field=models.CharField(blank=True, db_column='out1', max_length=10, null=True, verbose_name='OUT'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='reg_date',
            field=models.DateTimeField(auto_now=True, db_column='regdate', max_length=20),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='warehouse',
            field=models.CharField(blank=True, db_column='whouse', max_length=100, verbose_name='W/H'),
        ),
    ]
