# Generated by Django 3.2 on 2021-05-16 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0004_auto_20210516_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(blank=True, choices=[('GOWIN', 'GOWIN'), ('이강공사', '이강공사'), ('GLOVIS', 'GLOVIS'), ('오션마린', '오션마린'), ('MARUBISHI', 'MARUBISHI'), ('보성상사', '보성상사'), ('CENTRA', 'CENTRA'), ('SUNAMI', 'SUNAMI'), ('EUCO', 'EUCO'), ('DORVAL', 'DORVAL'), ('GOLTENS', 'GOLTENS'), ('SAEHAN', 'SAEHAN'), ('SHI OCEAN', 'SHI OCEAN'), ('KLCSM', 'KLCSM'), ('KNK', 'KNK'), ('MAN', 'MAN'), ('POSSM', 'POSSM'), ('DAN MO', 'DAN MO'), ('INTERGIS', 'INTERGIS'), ('KSS', 'KSS'), ('SEOYANG', 'SEOYANG'), ('STX', 'STX'), ('FORTUNE WILL', 'FORTUNE WILL'), ('SUNRIO', 'SUNRIO'), ('CMSHIP', 'CMSHIP'), ('JW', 'JW')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('L', 'L'), ('B', 'B'), ('D', 'D')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('START', 'START'), ('BLANK', 'BLANK'), ('COMPLETED', 'COMPLETED'), ('STAY1', 'STAY1'), ('STAY2', 'STAY2')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
    ]
