# Generated by Django 3.2 on 2021-04-23 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0004_auto_20210423_2330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='by',
            field=models.CharField(blank=True, choices=[('FDX', 'FDX'), ('DHL', 'DHL'), ('SFX', 'SFX'), ('TNT', 'TNT'), ('AIR', 'AIR'), ('SEA', 'SEA')], db_column='by1', max_length=50, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(choices=[('보성상사', '보성상사'), ('EUCO', 'EUCO'), ('POSSM', 'POSSM'), ('FORTUNE WILL', 'FORTUNE WILL'), ('SUNAMI', 'SUNAMI'), ('이강공사', '이강공사'), ('SHI OCEAN', 'SHI OCEAN'), ('INTERGIS', 'INTERGIS'), ('STX', 'STX'), ('DORVAL', 'DORVAL'), ('GOWIN', 'GOWIN'), ('KSS', 'KSS'), ('SUNRIO', 'SUNRIO'), ('오션마린', '오션마린'), ('MAN', 'MAN'), ('DAN MO', 'DAN MO'), ('GLOVIS', 'GLOVIS'), ('SEOYANG', 'SEOYANG'), ('CENTRA', 'CENTRA'), ('MARUBISHI', 'MARUBISHI'), ('SAEHAN', 'SAEHAN'), ('GOLTENS', 'GOLTENS'), ('CMSHIP', 'CMSHIP'), ('KNK', 'KNK'), ('KLCSM', 'KLCSM')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('L', 'L'), ('D', 'D'), ('B', 'B')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('STAY', 'STAY'), ('START', 'START'), ('COMPLETED', 'COMPLETED'), ('BLANK', 'BLANK')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='in_date',
            field=models.DateField(blank=True, db_column='in1', max_length=10, null=True, verbose_name='IN'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='out_date',
            field=models.DateField(blank=True, db_column='out1', max_length=10, null=True, verbose_name='OUT'),
        ),
    ]
