# Generated by Django 3.2 on 2021-04-25 05:53

import Shipment.models
from django.db import migrations, models
import override_existing


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0005_auto_20210423_2348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='by',
            field=models.CharField(blank=True, choices=[('AIR', 'AIR'), ('TNT', 'TNT'), ('DHL', 'DHL'), ('FDX', 'FDX'), ('SFX', 'SFX'), ('SEA', 'SEA')], db_column='by1', max_length=50, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(choices=[('STX', 'STX'), ('GOWIN', 'GOWIN'), ('KSS', 'KSS'), ('SAEHAN', 'SAEHAN'), ('DAN MO', 'DAN MO'), ('MAN', 'MAN'), ('GLOVIS', 'GLOVIS'), ('KNK', 'KNK'), ('POSSM', 'POSSM'), ('SUNAMI', 'SUNAMI'), ('SUNRIO', 'SUNRIO'), ('SHI OCEAN', 'SHI OCEAN'), ('이강공사', '이강공사'), ('KLCSM', 'KLCSM'), ('GOLTENS', 'GOLTENS'), ('MARUBISHI', 'MARUBISHI'), ('오션마린', '오션마린'), ('FORTUNE WILL', 'FORTUNE WILL'), ('INTERGIS', 'INTERGIS'), ('EUCO', 'EUCO'), ('CENTRA', 'CENTRA'), ('DORVAL', 'DORVAL'), ('SEOYANG', 'SEOYANG'), ('CMSHIP', 'CMSHIP'), ('보성상사', '보성상사')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('D', 'D'), ('L', 'L')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('START', 'START'), ('BLANK', 'BLANK'), ('STAY', 'STAY'), ('COMPLETED', 'COMPLETED')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='image',
            field=models.ImageField(blank=True, db_column='img', default='', null=True, storage=override_existing.OverrideExisting(), upload_to=Shipment.models.image_path, verbose_name='IMG'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='image1',
            field=models.ImageField(blank=True, db_column='img1', default='', null=True, storage=override_existing.OverrideExisting(), upload_to=Shipment.models.image_path),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='image2',
            field=models.ImageField(blank=True, db_column='img2', default='', null=True, storage=override_existing.OverrideExisting(), upload_to=Shipment.models.image_path),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='pdf_file',
            field=models.FileField(blank=True, db_column='pdf', default='', null=True, storage=override_existing.OverrideExisting(), upload_to=Shipment.models.pdf_path, verbose_name='PDF'),
        ),
    ]
