# Generated by Django 3.2 on 2021-05-19 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0005_auto_20210516_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='wh_timestamp',
            field=models.DateTimeField(blank=True, db_column='wh_timestamp1', null=True),
        ),
        migrations.AddField(
            model_name='shipment',
            name='wh_timestamp2',
            field=models.DateTimeField(blank=True, db_column='wh_timestamp2', null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(blank=True, choices=[('EUCO', 'EUCO'), ('FORTUNE WILL', 'FORTUNE WILL'), ('JW', 'JW'), ('SEOYANG', 'SEOYANG'), ('CMSHIP', 'CMSHIP'), ('GLOVIS', 'GLOVIS'), ('오션마린', '오션마린'), ('SAEHAN', 'SAEHAN'), ('SUNRIO', 'SUNRIO'), ('KNK', 'KNK'), ('DAN MO', 'DAN MO'), ('MAN', 'MAN'), ('보성상사', '보성상사'), ('SHI OCEAN', 'SHI OCEAN'), ('STX', 'STX'), ('MARUBISHI', 'MARUBISHI'), ('이강공사', '이강공사'), ('KLCSM', 'KLCSM'), ('DORVAL', 'DORVAL'), ('CENTRA', 'CENTRA'), ('GOLTENS', 'GOLTENS'), ('GOWIN', 'GOWIN'), ('KSS', 'KSS'), ('SUNAMI', 'SUNAMI'), ('INTERGIS', 'INTERGIS'), ('POSSM', 'POSSM')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('D', 'D'), ('L', 'L'), ('B', 'B')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('STAY1', 'STAY1'), ('COMPLETED', 'COMPLETED'), ('STAY2', 'STAY2'), ('BLANK', 'BLANK'), ('START', 'START')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
    ]
