# Generated by Django 3.2 on 2021-04-26 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0006_auto_20210425_1453'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='by',
            field=models.CharField(blank=True, choices=[('SFX', 'SFX'), ('AIR', 'AIR'), ('DHL', 'DHL'), ('SEA', 'SEA'), ('FDX', 'FDX'), ('TNT', 'TNT')], db_column='by1', max_length=50, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(choices=[('MAN', 'MAN'), ('MARUBISHI', 'MARUBISHI'), ('STX', 'STX'), ('FORTUNE WILL', 'FORTUNE WILL'), ('SAEHAN', 'SAEHAN'), ('KNK', 'KNK'), ('CENTRA', 'CENTRA'), ('SUNAMI', 'SUNAMI'), ('보성상사', '보성상사'), ('SHI OCEAN', 'SHI OCEAN'), ('INTERGIS', 'INTERGIS'), ('DAN MO', 'DAN MO'), ('DORVAL', 'DORVAL'), ('CMSHIP', 'CMSHIP'), ('SUNRIO', 'SUNRIO'), ('GLOVIS', 'GLOVIS'), ('KSS', 'KSS'), ('KLCSM', 'KLCSM'), ('SEOYANG', 'SEOYANG'), ('GOLTENS', 'GOLTENS'), ('POSSM', 'POSSM'), ('GOWIN', 'GOWIN'), ('이강공사', '이강공사'), ('오션마린', '오션마린'), ('EUCO', 'EUCO')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('L', 'L'), ('B', 'B'), ('D', 'D')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'COMPLETED'), ('BLANK', 'BLANK'), ('STAY', 'STAY'), ('START', 'START')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
    ]
