# Generated by Django 3.2 on 2021-05-19 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0006_auto_20210519_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(blank=True, choices=[('SEOYANG', 'SEOYANG'), ('보성상사', '보성상사'), ('DAN MO', 'DAN MO'), ('FORTUNE WILL', 'FORTUNE WILL'), ('INTERGIS', 'INTERGIS'), ('KNK', 'KNK'), ('MAN', 'MAN'), ('MARUBISHI', 'MARUBISHI'), ('GOLTENS', 'GOLTENS'), ('SAEHAN', 'SAEHAN'), ('SHI OCEAN', 'SHI OCEAN'), ('STX', 'STX'), ('POSSM', 'POSSM'), ('CMSHIP', 'CMSHIP'), ('KSS', 'KSS'), ('이강공사', '이강공사'), ('오션마린', '오션마린'), ('SUNAMI', 'SUNAMI'), ('EUCO', 'EUCO'), ('SUNRIO', 'SUNRIO'), ('CENTRA', 'CENTRA'), ('GLOVIS', 'GLOVIS'), ('KLCSM', 'KLCSM'), ('GOWIN', 'GOWIN'), ('DORVAL', 'DORVAL'), ('JW', 'JW')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('L', 'L'), ('D', 'D'), ('B', 'B')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('COMPLETED', 'COMPLETED'), ('BLANK', 'BLANK'), ('STAY1', 'STAY1'), ('START', 'START'), ('STAY2', 'STAY2')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='wh_timestamp',
            field=models.DateTimeField(blank=True, db_column='wh_timestamp1', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='wh_timestamp2',
            field=models.DateTimeField(blank=True, db_column='wh_timestamp2', max_length=20, null=True),
        ),
    ]
