# Generated by Django 3.2 on 2021-05-25 19:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0002_auto_20210430_0000'),
        ('Shipment', '0007_auto_20210519_1622'),
    ]

    operations = [
    ]
