# Generated by Django 3.2 on 2021-05-26 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0008_merge_0002_auto_20210430_0000_0007_auto_20210519_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='by',
            field=models.CharField(blank=True, db_column='by1', max_length=50, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(blank=True, choices=[('SAEHAN', 'SAEHAN'), ('STX', 'STX'), ('SEOYANG', 'SEOYANG'), ('JW', 'JW'), ('MAN', 'MAN'), ('SUNRIO', 'SUNRIO'), ('KSS', 'KSS'), ('보성상사', '보성상사'), ('CENTRA', 'CENTRA'), ('이강공사', '이강공사'), ('DORVAL', 'DORVAL'), ('GOWIN', 'GOWIN'), ('SHI OCEAN', 'SHI OCEAN'), ('SUNAMI', 'SUNAMI'), ('INTERGIS', 'INTERGIS'), ('KNK', 'KNK'), ('MARUBISHI', 'MARUBISHI'), ('DAN MO', 'DAN MO'), ('CMSHIP', 'CMSHIP'), ('KLCSM', 'KLCSM'), ('POSSM', 'POSSM'), ('오션마린', '오션마린'), ('EUCO', 'EUCO'), ('GLOVIS', 'GLOVIS'), ('GOLTENS', 'GOLTENS'), ('FORTUNE WILL', 'FORTUNE WILL')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('D', 'D'), ('L', 'L'), ('B', 'B')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('START', 'START'), ('BLANK', 'BLANK'), ('COMPLETED', 'COMPLETED'), ('STAY2', 'STAY2'), ('STAY1', 'STAY1')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
    ]
