# Generated by Django 3.2 on 2021-04-26 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0008_auto_20210427_0023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='by',
            field=models.CharField(blank=True, choices=[('SEA', 'SEA'), ('FDX', 'FDX'), ('DHL', 'DHL'), ('TNT', 'TNT'), ('SFX', 'SFX'), ('AIR', 'AIR')], db_column='by1', max_length=50, verbose_name='BY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(blank=True, choices=[('DORVAL', 'DORVAL'), ('CMSHIP', 'CMSHIP'), ('GLOVIS', 'GLOVIS'), ('KLCSM', 'KLCSM'), ('STX', 'STX'), ('SEOYANG', 'SEOYANG'), ('이강공사', '이강공사'), ('FORTUNE WILL', 'FORTUNE WILL'), ('SUNRIO', 'SUNRIO'), ('GOWIN', 'GOWIN'), ('INTERGIS', 'INTERGIS'), ('MAN', 'MAN'), ('EUCO', 'EUCO'), ('KNK', 'KNK'), ('SUNAMI', 'SUNAMI'), ('SHI OCEAN', 'SHI OCEAN'), ('보성상사', '보성상사'), ('DAN MO', 'DAN MO'), ('GOLTENS', 'GOLTENS'), ('KSS', 'KSS'), ('MARUBISHI', 'MARUBISHI'), ('오션마린', '오션마린'), ('POSSM', 'POSSM'), ('CENTRA', 'CENTRA'), ('SAEHAN', 'SAEHAN')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('START', 'START'), ('COMPLETED', 'COMPLETED'), ('BLANK', 'BLANK'), ('STAY', 'STAY')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
    ]
