# Generated by Django 3.2 on 2021-05-26 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0009_auto_20210526_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(blank=True, choices=[('CMSHIP', 'CMSHIP'), ('GOWIN', 'GOWIN'), ('EUCO', 'EUCO'), ('보성상사', '보성상사'), ('MARUBISHI', 'MARUBISHI'), ('CENTRA', 'CENTRA'), ('KSS', 'KSS'), ('SHI OCEAN', 'SHI OCEAN'), ('SUNRIO', 'SUNRIO'), ('FORTUNE WILL', 'FORTUNE WILL'), ('SAEHAN', 'SAEHAN'), ('오션마린', '오션마린'), ('KLCSM', 'KLCSM'), ('이강공사', '이강공사'), ('JW', 'JW'), ('GOLTENS', 'GOLTENS'), ('INTERGIS', 'INTERGIS'), ('SEOYANG', 'SEOYANG'), ('DORVAL', 'DORVAL'), ('MAN', 'MAN'), ('DAN MO', 'DAN MO'), ('GLOVIS', 'GLOVIS'), ('STX', 'STX'), ('SUNAMI', 'SUNAMI'), ('POSSM', 'POSSM'), ('KNK', 'KNK')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('B', 'B'), ('L', 'L'), ('D', 'D')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('START', 'START'), ('STAY1', 'STAY1'), ('BLANK', 'BLANK'), ('STAY2', 'STAY2'), ('COMPLETED', 'COMPLETED')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
    ]
