# Generated by Django 3.2 on 2021-05-26 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0010_auto_20210526_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='warehouse_lastupdate',
            field=models.CharField(blank=True, db_column='whouse_lastupdate', default='', max_length=100, verbose_name='W/H'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(blank=True, choices=[('GLOVIS', 'GLOVIS'), ('GOWIN', 'GOWIN'), ('KSS', 'KSS'), ('SAEHAN', 'SAEHAN'), ('MAN', 'MAN'), ('오션마린', '오션마린'), ('GOLTENS', 'GOLTENS'), ('KNK', 'KNK'), ('CMSHIP', 'CMSHIP'), ('이강공사', '이강공사'), ('POSSM', 'POSSM'), ('SHI OCEAN', 'SHI OCEAN'), ('보성상사', '보성상사'), ('FORTUNE WILL', 'FORTUNE WILL'), ('DORVAL', 'DORVAL'), ('JW', 'JW'), ('INTERGIS', 'INTERGIS'), ('DAN MO', 'DAN MO'), ('KLCSM', 'KLCSM'), ('MARUBISHI', 'MARUBISHI'), ('STX', 'STX'), ('SUNRIO', 'SUNRIO'), ('CENTRA', 'CENTRA'), ('SEOYANG', 'SEOYANG'), ('SUNAMI', 'SUNAMI'), ('EUCO', 'EUCO')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='division',
            field=models.CharField(blank=True, choices=[('L', 'L'), ('B', 'B'), ('D', 'D')], db_column='division', max_length=10, verbose_name='DIVISION'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('BLANK', 'BLANK'), ('START', 'START'), ('STAY2', 'STAY2'), ('COMPLETED', 'COMPLETED'), ('STAY1', 'STAY1')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
    ]
