# Generated by Django 3.2 on 2021-05-26 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Shipment', '0011_auto_20210526_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='company',
            field=models.CharField(blank=True, choices=[('DAN MO', 'DAN MO'), ('EUCO', 'EUCO'), ('MARUBISHI', 'MARUBISHI'), ('POSSM', 'POSSM'), ('SEOYANG', 'SEOYANG'), ('SAEHAN', 'SAEHAN'), ('SUNAMI', 'SUNAMI'), ('오션마린', '오션마린'), ('KNK', 'KNK'), ('KSS', 'KSS'), ('JW', 'JW'), ('GOWIN', 'GOWIN'), ('KLCSM', 'KLCSM'), ('INTERGIS', 'INTERGIS'), ('STX', 'STX'), ('CENTRA', 'CENTRA'), ('SHI OCEAN', 'SHI OCEAN'), ('이강공사', '이강공사'), ('CMSHIP', 'CMSHIP'), ('보성상사', '보성상사'), ('FORTUNE WILL', 'FORTUNE WILL'), ('SUNRIO', 'SUNRIO'), ('DORVAL', 'DORVAL'), ('MAN', 'MAN'), ('GOLTENS', 'GOLTENS'), ('GLOVIS', 'GLOVIS')], db_column='company', max_length=100, verbose_name='COMPANY'),
        ),
        migrations.AlterField(
            model_name='shipment',
            name='flag_status',
            field=models.CharField(blank=True, choices=[('STAY2', 'STAY2'), ('STAY1', 'STAY1'), ('START', 'START'), ('BLANK', 'BLANK'), ('COMPLETED', 'COMPLETED')], db_column='flg', max_length=10, verbose_name='STATE'),
        ),
    ]
