# Generated by Django 2.2.10 on 2021-04-20 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('userID', models.CharField(default=None, max_length=30, unique=True, verbose_name='Account ID')),
                ('password', models.CharField(default=None, max_length=30, verbose_name='Password')),
                ('email', models.EmailField(blank=True, default='', max_length=30, verbose_name='Email')),
                ('companyName', models.CharField(blank=True, default='', max_length=30, verbose_name='Company')),
                ('vesselList', models.TextField(blank=True, default='', max_length=1200, verbose_name='Vessel List')),
                ('permission', models.CharField(choices=[('Read + Modify', 'Read + Modify'), ('Read Only', 'Read Only')], default='Read + Modify', max_length=30, verbose_name='Permission')),
                ('isOpr', models.BooleanField(default=False, verbose_name='Is Operator')),
                ('isSpl', models.BooleanField(default=False, verbose_name='Is Supplier')),
                ('isCpn', models.BooleanField(default=False, verbose_name='Is Company')),
                ('dateSignUp', models.DateField(auto_now=True, verbose_name='Date Signed Up')),
            ],
            options={
                'db_table': 'account_table',
            },
        ),
    ]
