# Generated by Django 3.2 on 2021-04-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='account',
            name='permission',
            field=models.CharField(choices=[('Read Only', 'Read Only'), ('Read + Modify', 'Read + Modify')], default='Read + Modify', max_length=30, verbose_name='Permission'),
        ),
    ]
