# Generated by Django 3.2 on 2021-04-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210421_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='rawPassword',
            field=models.CharField(default=None, max_length=30, verbose_name='Raw Password'),
        ),
    ]
