# Generated by Django 3.2 on 2021-04-21 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_account_rawpassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='permission',
            field=models.CharField(choices=[('Read + Modify', 'Read + Modify'), ('Read Only', 'Read Only')], default='Read + Modify', max_length=30, verbose_name='Permission'),
        ),
    ]
