# Generated by Django 3.2 on 2021-04-21 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_alter_account_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default=None, max_length=80, verbose_name='Password'),
        ),
        migrations.AlterField(
            model_name='account',
            name='permission',
            field=models.CharField(choices=[('Read + Modify', 'Read + Modify'), ('Read Only', 'Read Only')], default='Read + Modify', max_length=30, verbose_name='Permission'),
        ),
    ]
