# Generated by Django 3.2 on 2021-04-21 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_auto_20210421_1947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='password',
            field=models.CharField(default=None, max_length=100, verbose_name='Password'),
        ),
    ]
