# Generated by Django 3.2 on 2021-04-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0011_alter_account_permission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='permission',
            field=models.CharField(choices=[('Read Only', 'Read Only'), ('Read + Modify', 'Read + Modify')], default='Read + Modify', max_length=30, verbose_name='Permission'),
        ),
    ]
